provider:
  name: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-token
        key: api-token

sources:
  - service
  - ingress

domainFilters:
  - ismaaeelahmed.co.uk

policy: sync

txtOwnerId: eks-project

logLevel: info

metrics:
  enabled: true